# Generated by Django 5.1.3 on 2024-12-12 21:56

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.RemoveField(
            model_name='news',
            name='author_facebook',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author_instagram',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author_telegram',
        ),
        migrations.RemoveField(
            model_name='news',
            name='author_text',
        ),
        migrations.RemoveField(
            model_name='news',
            name='capital_letter',
        ),
        migrations.RemoveField(
            model_name='news',
            name='detail_image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='home_image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='related_image',
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default=django.utils.timezone.now, force_format='WEBP', help_text='preferred size: 790x510', keep_meta=True, quality=95, scale=None, size=[790, 510], upload_to='news/%Y/%m', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='consulting.newscategory', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
        migrations.AlterModelTable(
            name='news',
            table='news',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('message', models.TextField(verbose_name='message')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='consulting.news', verbose_name='news')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='consulting.comment', verbose_name='parent')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
                'db_table': 'comment',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
