# Generated by Django 5.1.3 on 2024-12-12 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0002_alter_news_options_remove_news_author_facebook_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
