# Generated by Django 5.1.3 on 2024-12-12 23:47

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('slug', models.SlugField(blank=True, max_length=256, null=True, unique=True, verbose_name='slug')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', help_text='preferred size: 720x720', keep_meta=True, quality=97, scale=None, size=[720, 720], upload_to='student/%Y/%m', verbose_name='image')),
                ('visa_type', models.CharField(max_length=256, verbose_name='visa type')),
                ('budget', models.CharField(blank=True, max_length=256, null=True, verbose_name='budget')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='date')),
                ('text', ckeditor.fields.RichTextField(verbose_name='text')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='consulting.subcategory', verbose_name='country')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='consulting.programs', verbose_name='university')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'student',
            },
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
