# Generated by Django 5.1.3 on 2024-12-13 00:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0005_comment_created_at_comment_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='visa_type',
        ),
        migrations.AddField(
            model_name='student',
            name='program_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=256, verbose_name='program type'),
            preserve_default=False,
        ),
    ]
