# Generated by Django 5.1.3 on 2024-12-13 10:15

import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0006_remove_student_visa_type_student_program_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('image', django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', help_text='preferred size: 790x510', keep_meta=True, quality=97, scale=None, size=[790, 510], upload_to='program/%Y/%m', verbose_name='image')),
                ('specialisation', models.CharField(help_text='e.g: IT, Law, Business', max_length=256, verbose_name='specialisation')),
                ('local_rating', models.CharField(max_length=256, verbose_name='local rating')),
                ('global_rating', models.CharField(max_length=256, verbose_name='global rating')),
                ('date_opened', models.CharField(max_length=256, verbose_name='date opened')),
                ('text', ckeditor.fields.RichTextField(verbose_name='text')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='published date')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_createdby', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modifiedby', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='consulting.subcategory', verbose_name='subcategory')),
            ],
            options={
                'verbose_name': 'program',
                'verbose_name_plural': 'programs',
                'db_table': 'program',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='consulting.program', verbose_name='university'),
        ),
        migrations.DeleteModel(
            name='Programs',
        ),
    ]
