# Generated by Django 5.1.3 on 2024-12-13 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0008_alter_program_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='consulting.subcategory', verbose_name='subcategory'),
        ),
    ]
