# Generated by Django 5.1.3 on 2024-12-20 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0011_studentcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcomment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='consulting.student', verbose_name='student'),
        ),
    ]
